/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dsn_dev_java_Nativecalls_dsn_task_priority_t */

#ifndef _Included_dsn_dev_java_Nativecalls_dsn_task_priority_t
#define _Included_dsn_dev_java_Nativecalls_dsn_task_priority_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
