/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dsn_dev_java_Nativecalls */

#ifndef _Included_dsn_dev_java_Nativecalls
#define _Included_dsn_dev_java_Nativecalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_register_app_role_managed
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1register_1app_1role_1managed
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_mimic_app
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1mimic_1app
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_run
 * Signature: (I[Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1run
  (JNIEnv *, jclass, jint, jobjectArray, jboolean);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_run_config
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1run_1config
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_address_build
 * Signature: (Ljava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1address_1build
  (JNIEnv *, jclass, jstring, jshort);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_address_build_ipv4
 * Signature: (IS)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1address_1build_1ipv4
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_address_build_uri
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1address_1build_1uri
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_address_build_group
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1address_1build_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_uri_build
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1uri_1build
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_uri_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1uri_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_build
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1build
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_add
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1add
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_remove
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1remove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_set_leader
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1set_1leader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_get_leader
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1get_1leader
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_is_leader
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1is_1leader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_next
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1next
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_group_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1group_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_primary_address
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1primary_1address
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_ipv4_from_host
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1ipv4_1from_1host
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_ipv4_local
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1ipv4_1local
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_address_to_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1address_1to_1string
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_now_ns
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1now_1ns
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_random64
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1random64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_coredump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1coredump
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_crc32_compute
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1crc32_1compute
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_crc32_concatenate
 * Signature: (IIIJIIJ)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1crc32_1concatenate
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_log2
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1log2
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_log_get_start_level2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1log_1get_1start_1level2
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_error_register
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1error_1register
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_error_to_string
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1error_1to_1string
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_threadpool_code_register
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1threadpool_1code_1register
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_threadpool_code_to_string
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1threadpool_1code_1to_1string
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_threadpool_code_from_string
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1threadpool_1code_1from_1string
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_threadpool_code_max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1threadpool_1code_1max
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_register2
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1register2
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_query2
 * Signature: (I[I[I[I)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1query2
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_set_threadpool
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1set_1threadpool
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_set_priority2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1set_1priority2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_to_string
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1to_1string
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_from_string
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1from_1string
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_code_max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1code_1max
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_type_to_string2
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1type_1to_1string2
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_priority_to_string2
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1priority_1to_1string2
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_config_get_value_string
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dsn_dev_java_Nativecalls_dsn_1config_1get_1value_1string
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_config_get_value_bool
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1config_1get_1value_1bool
  (JNIEnv *, jclass, jstring, jstring, jboolean, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_config_get_value_uint64
 * Signature: (Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1config_1get_1value_1uint64
  (JNIEnv *, jclass, jstring, jstring, jlong, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_config_get_value_double
 * Signature: (Ljava/lang/String;Ljava/lang/String;DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_dsn_dev_java_Nativecalls_dsn_1config_1get_1value_1double
  (JNIEnv *, jclass, jstring, jstring, jdouble, jstring);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_config_get_all_keys2
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1config_1get_1all_1keys2
  (JNIEnv *, jclass, jstring, jobjectArray, jintArray);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_exlock_create
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1exlock_1create
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_exlock_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1exlock_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_exlock_lock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1exlock_1lock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_exlock_try_lock
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1exlock_1try_1lock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_exlock_unlock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1exlock_1unlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rwlock_nr_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rwlock_1nr_1create
  (JNIEnv *, jclass);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rwlock_nr_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rwlock_1nr_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rwlock_nr_lock_read
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rwlock_1nr_1lock_1read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rwlock_nr_unlock_read
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rwlock_1nr_1unlock_1read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rwlock_nr_lock_write
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rwlock_1nr_1lock_1write
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rwlock_nr_unlock_write
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rwlock_1nr_1unlock_1write
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_semaphore_create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1semaphore_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_semaphore_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1semaphore_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_semaphore_signal
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1semaphore_1signal
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_semaphore_wait
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1semaphore_1wait
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_semaphore_wait_timeout
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1semaphore_1wait_1timeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_create
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1create
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_create_timer
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1create_1timer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_add_ref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1add_1ref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_release_ref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1release_1ref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_call
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1call
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_cancel
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1cancel
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_cancel3
 * Signature: (JZ[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1cancel3
  (JNIEnv *, jclass, jlong, jboolean, jbooleanArray);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_wait
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1wait
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_wait_timeout
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1wait_1timeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_error
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1error
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_tracker_create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1tracker_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_tracker_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1tracker_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_tracker_wait_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1tracker_1wait_1all
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_task_tracker_cancel_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1task_1tracker_1cancel_1all
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_create_request
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1create_1request
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_create_response
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1create_1response
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_add_ref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1add_1ref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_release_ref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1release_1ref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_update_request
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1update_1request
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_query_request2
 * Signature: (JI[I)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1query_1request2
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_read
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_write
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_body_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1body_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_rw_ptr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1rw_1ptr
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_from_address
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1from_1address
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_msg_to_address
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1msg_1to_1address
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_register_handler
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1register_1handler
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_unregiser_handler
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1unregiser_1handler
  (JNIEnv *, jclass, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_create_response_task
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1create_1response_1task
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_call
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1call
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_call_wait
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1call_1wait
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_call_one_way
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1call_1one_1way
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_reply
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1reply
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_get_response
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1get_1response
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_rpc_enqueue_response
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1rpc_1enqueue_1response
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_open
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_create_aio_task
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1create_1aio_1task
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_read
 * Signature: (J[BIJJJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_write
 * Signature: (J[BIJJJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_copy_remote_directory
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZJJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1copy_1remote_1directory
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_copy_remote_files
 * Signature: (JLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;ZJJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1copy_1remote_1files
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jstring, jboolean, jlong, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_get_io_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1get_1io_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dsn_dev_java_Nativecalls
 * Method:    dsn_file_task_enqueue
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_dsn_dev_java_Nativecalls_dsn_1file_1task_1enqueue
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
