/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dsn_dev_java_Nativecalls_dsn_app_info */

#ifndef _Included_dsn_dev_java_Nativecalls_dsn_app_info
#define _Included_dsn_dev_java_Nativecalls_dsn_app_info
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
